language: node_js

branches:
  only:
    - master

node_js:
  - "8.10"
  - "10.18"
  - "12.13"

script:
  - npm run lint

jobs:
  include:
    - stage: build-and-deploy
      node_js: "10.18"
      script:
        - npm run build && npm run semantic-release

stages:
  - Test
  - name: build-and-deploy
    if: branch = master AND type = push

